# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb0ac14aadc28fc02cef423fab4cd57d7434e326a75325cc6fbcda4b1ae0ff209437c0c8afdb690e241926452a143f4c793b69a7d80e6639c5984554f4783d4
  github_client_id: <%= ENV["GITHUB_CLIENT_ID_DEV"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET_DEV"] %>
  action_mailer_password: <%= ENV["ACTION_MAILER_PASSWORD"] %>

  # Rails.application.secrets.github_client_secret

test:
  secret_key_base: 7b224b78f00e0477be643fe131e66b82888ac89a81b43621425fb1dea23ceb0f2ff77295235e56dcea83c8baf6ccd9f409cd1a8cc9a261941bf1d7a7f3c4c169
  github_client_id: <%= ENV["GITHUB_CLIENT_ID_DEV"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET_DEV"] %>
  action_mailer_password: <%= ENV["ACTION_MAILER_PASSWORD"] %>
  

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  action_mailer_password: <%= ENV["ACTION_MAILER_PASSWORD"] %>